### PR TITLE
Implement opcode BLOBBASEFEE

### LINKED ISSUE #56: Opcode: BLOBBASEFEE

### PR DESCRIPTION
**Pull request by JulianVentura**
Closes #56 
This PR implements the BLOBBASEFEE opcode with its tests.

### CODE REVIEW

**Review by ricomateo — COMMENTED** [review]
LGTM

**Review by TomasArrachea — CHANGES_REQUESTED** [review]
Please update the Readme file

**Review by TomasArrachea — APPROVED** [review]
LGTM
@MegaRedHand

**Review by MegaRedHand — APPROVED** [review]
LGTM

**Comment by JulianVentura** [comment]
> Please update the Readme file

**Comment by JulianVentura** [comment]
> Please update the Readme file

Good catch!

**Comment by JulianVentura** [comment]
Accidentaly closed the PR 😄

**Pull request merged**
