### PR TITLE
Ef tests fix

### PR DESCRIPTION
**Pull request by belfortep**
Closes https://github.com/lambdaclass/evm_mlir/issues/381
## Summary
This PR fix an issue with the parsing of the code from the EF
## Changes
- Added a function to parse from the hexadecimal string to the hexadecimal value
- Deleted from ignored groups all workings tests
- Added tests that started to fail
- Can tests code without a `to` address

### CODE REVIEW

**Review by lazcanoluca — APPROVED** [review]

**Comment by lazcanoluca** [comment]
> Added tests that started to fail

I don't understand this, are these new tests, or tests that began failing because of the PR's changes?

**Comment by belfortep** [comment]
> > Added tests that started to fail
> 
> I don't understand this, are these new tests, or tests that began failing because of the PR's changes?

Yes, these are tests that began failing because of the changes in the PR

**Comment by lazcanoluca** [comment]
Oh okay I get it! I hadn't noticed the HashSet was returned from the `get_ignored_groups()` function.

**Review by JulianVentura — APPROVED** [review]
LGTM

**Pull request merged**
